#include <stdio.h>
/**
 * main - Entry point
 * Description: Fibonacci sequence is generated by adding the previous two terms.
 * Return: Always 0
 */
int main(void)
{
	int i, j, k, l, sum = 0;

	i = 1;
	j = 1;
	k = i + j;
	l = 4000000;

	While (k < 4000000)
		sum = sum + k;
	i = j + k;
	j = i +k;
	k = i + j;
	printf("\n", sum);
	return (0);
}
