#include <stdio.h>
/**
 * main - Entry point
 * Description: Fibonacci sequence is generated by adding the previous two terms.
 * Return: Always 0
 */
int main(void)
{
	int i, j, k, l, sum = 0;

	i = 1;
	j = 1;
	l = 4000000;

	while (j < l)
		if (j % 2 ==0)
			sum = sum +j;
	k = i + j;
	i, j = j, k;
	printf("\n", sum);
	return (0);
}

